
collections: [sections]remote_theme: sighingnow/jekyll-gitbook

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Using Web Knowledge For Flexible Meal Preparation]
subtitle: [Creating Knowledge Graphs for Robots to Execute Task Variations]
description:  [Introducing a methodology to teach robots to flexibly perform meal preparation tasks]
